tensorleap/leap-cli

cmd/local/install.go
cmd/local/upgrade.go
pkg/helm/install.go
pkg/helm/upgrade.go
pkg/helm/utils.go
pkg/k3d/cluster.go
pkg/k3d/cluster_test.go
pkg/k3d/registry.go
pkg/local/upgrade.go

implement upgrade cmd

---

cmd/local/install.go
cmd/local/uninstall.go
cmd/local/upgrade.go
cmd/root.go
docgen/docgen.go
go.mod
go.sum
pkg/helm/install.go
pkg/helm/upgrade.go
pkg/helm/utils.go
pkg/k3d/cluster.go
pkg/k3d/log.go
pkg/k3d/registry.go
pkg/k8s/log.go
pkg/local/install.go
pkg/local/utils.go
pkg/log/log.go

- Update packages
- Add log
- Use the new logger
- Add background logger for installing uninstall and upgrade commands
Currently, we are doing nothing in the background log - We will save it for using it in case of an error (anther task)

add logger and setup background logger

---

cmd/local/install.go
cmd/local/uninstall.go
cmd/local/upgrade.go
pkg/helm/utils.go
pkg/local/install.go
pkg/local/upgrade.go
pkg/local/utils.go
pkg/log/helpers.go
pkg/log/log.go
pkg/log/output.go

- Suport multi outputs for verbose log
- Add verbose logger
- Add helper for connecting file to verbose logger
- Use verbose logger in helm
- Move init var to utils and add logs subdirectory
- Add local.Setup for init var dir, verbose logger and connect it into a file
- Use Setup function

save background logs

---

cmd/datasets/push.go
go.mod
go.sum
pkg/config/datasetconfig.go

- Add SetDatasetConfig
- Add library for user interactions
- Add function that add dataset if not exists

create dataset on push

---

cmd/auth/login.go
cmd/auth/logout.go
cmd/auth/whoami.go
cmd/datasets/list.go
cmd/datasets/listVersions.go
cmd/datasets/push.go
cmd/local/install.go
cmd/models/import.go
cmd/root.go
pkg/api/apiClient.go
pkg/auth/auth.go
pkg/auth/config.go
pkg/config/config.go

- Move config to auth package
- Login after install

login after installation

---

cmd/local/uninstall.go
pkg/docker/utils.go
pkg/k3d/cluster.go
pkg/k3d/registry.go
pkg/local/utils.go

- Add remove registry
- Add purge

remove registry and data on uninstall

---

cmd/code/push.go
cmd/root.go
cmd/secrets/list.go
cmd/secrets/root.go
pkg/api/files_test.go
pkg/code/config.go
pkg/local/files_test.go

- Add secrets list command
- Support dataset push with secret id
- Skip temporary failed tests

support secrets

---

cmd/code/push.go
cmd/projects/push.go
go.mod
go.sum
pkg/api/wait.go
pkg/code/api.go
pkg/code/utils.go
pkg/log/helpers.go

- Add spiner package
- Add wait code integration status function
- Add function that print the parser error
- Use these function in code and project push

wait to parser

---

cmd/code/push.go
cmd/projects/push.go
pkg/code/api.go
pkg/code/utils.go
pkg/local/files.go
pkg/local/files_test.go

- Add file checksup function
- Add CompereCode and push code for code push and project push
- use push code to check if code is change

check code change

---

pkg/code/utils.go

- Add static bindings.yam file to include paths

include bindings file

---

.github/workflows/ci.yml

uncomment fmt check

---

cmd/server/upgrade.go
pkg/helm/upgrade.go
pkg/helm/utils.go
pkg/helm/utils_test.go
pkg/server/install.go

- Add utils for getting values and create new values from them
- Use the new functions for upgrade helm

fix unupdated images

---

cmd/server/run.go
cmd/server/stop.go
cmd/server/upgrade.go
pkg/k3d/cluster.go
pkg/server/upgrade.go

- Add run and stop functions, on install if the cluster exists restart it
- Update update command to restart cluser before upgrade
- Add run and stop command

add run and stop

---

cmd/server/install.go
cmd/server/upgrade.go
pkg/helm/utils.go
pkg/helm/utils_test.go
pkg/k3d/cluster.go
pkg/server/install.go

- Add function that create kube config temporary
- Get path to kubeconfig in helm config
- Update upgrade and istall commands

not depend on local kubeconfig

---

cmd/secrets/create.go
cmd/secrets/delete.go
cmd/secrets/list.go
pkg/entity/helpers.go
pkg/secret/api.go
pkg/secret/utils.go

- Add secret api and utils
- Add create and delete commands

add delete secret cmds

---

cmd/code/create.go
cmd/code/init.go
cmd/code/pull.go
cmd/code/push.go
cmd/projects/init.go
cmd/projects/push.go
cmd/projects/set_secret.go
cmd/secrets/create.go
cmd/secrets/delete.go
cmd/secrets/list.go
cmd/secrets/set.go
pkg/secret/api.go
pkg/secret/utils.go
pkg/workspace/config.go
pkg/workspace/template/leap.yaml

- Rename to AskForNewSecret and GetSecretList
- Add secret id to template and rename to secret id
- Sync and validate secret id on init and push commands
- Add set secret command

add secret on project init

---

cmd/code/list.go
cmd/projects/list.go
cmd/secrets/list.go
pkg/secret/utils.go

- Add shortcat ls for list
- Fix add secret bug

add shortcut for list

---

cmd/server/install.go
cmd/server/upgrade.go
pkg/helm/chart/chart.go
pkg/helm/install.go
pkg/helm/upgrade.go
pkg/helm/utils.go
pkg/server/airgap/pack.go
pkg/server/manifest/generate.go
pkg/server/manifest/utils.go
pkg/server/utils.go

- Move functions and add load chart function
- Load the helm chart in the begining instead of in the install and upgrade

fix tensorleap helm

---

cmd/cli/upgrade.go
cmd/server/install.go
cmd/server/root.go
cmd/server/upgrade.go
cmd/server/utils.go
go.mod
go.sum
pkg/cli/utils.go

- Update mod
- Share upgrade CLI command
- Upgate installation commands - map the installation error

Update installation v0.0.2

---

cmd/auth/login.go
cmd/auth/logout.go
cmd/auth/select.go
cmd/auth/whoami.go
cmd/root.go
cmd/server/utils.go
pkg/auth/api.go
pkg/auth/auth.go
pkg/auth/config.go
pkg/auth/utils.go

- Remove binary file
- Refactor auth pkg - support multiple envs
- Integrate the cli commands, and add auth select to switch between envs
- Integrate the installation login
- Integrate ctx creation

Support multi environments

---

pkg/api/files.go
pkg/code/api.go
pkg/code/utils.go
pkg/model/api.go
pkg/project/api.go

- Check the response status and add content-type - seems to be required for s3
- Send the file size

fix upload file for s3

---

.github/workflows/ci.yml

updating the versions of various obsolete actions

updating some github actions versions due to warnings

---

go.mod
go.sum
pkg/auth/utils.go

- Update version
- Change the logic of isLocalUrl

update installer 0.0.11

---

cmd/server/install.go
cmd/server/reinstall.go
cmd/server/root.go
cmd/server/uninstall.go
cmd/server/upgrade.go
cmd/server/utils.go
go.mod
go.sum
pkg/auth/config.go
pkg/auth/utils.go
pkg/config/config.go

- **Move save to config**
- **Add function that init data dir**
- **Use the init function**

make storage dir configurable

---

.github/workflows/ci.yml
cmd/root.go
cmd/server/utils.go

- Initate new context at run command
- Skip local login

stateless context

---

pkg/api/files.go
pkg/api/wait.go
pkg/hub/storage.go
pkg/log/helpers.go
pkg/project/api.go

- **Add update progress**
- **Add ProgressReader and use it in UploadFile**

adding progress to uploaded file

---

cmd/code/pull.go
cmd/projects/init.go
go.mod
go.sum
pkg/code/utils.go
pkg/local/files.go
pkg/local/files_test.go

- **Support mapping only on code pull**
- **Add unit test**

pull mapping only

---

cmd/code/init.go
cmd/code/pull.go
cmd/projects/init.go
pkg/code/api.go
pkg/code/utils.go
pkg/workspace/config.go

- **Add flag sync for python version**
- **Add python flag to the cli commands**

adding python version 2

---

cmd/code/info.go
cmd/models/import.go
cmd/projects/info.go
cmd/projects/push.go
go.mod
go.sum
pkg/code/utils.go

- **Improve transform input description**
- **Support code info**
- **Support projects info**
- **Update server**

cli clarifications

---

cmd/server/info.go
go.mod
go.sum

- **Install server pck**
- **Use tensorleap chart version in server info**

server chart version
